Pages enhancements
strandls/biodiv-pages pull request #23
Opened 2024-02-21 08:40 UTC by arunasd463

2024-02-22 15:25 UTC, prakhar-s requested changes
Please write commands/scripts for all the backend tasks you mentioned in the PR description in a proper deployment ticket.

2024-02-22 15:25 UTC, prakhar-s commented on src/main/java/com/strandls/pages/util/AuthUtility.java
have we made sure that all older `isAdmin(HttpServletRequest request)` function call references (if any) have also been changed to the new definition?

2024-02-23 03:59 UTC, arunasd463 commented on src/main/java/com/strandls/pages/util/AuthUtility.java
Yes , i checked the function references , Its been used for pages only .

2024-02-23 07:53 UTC, prakhar-s approved these changes

2024-02-23 07:55 UTC, merged